from api_key import api_key
from langchain_openai import ChatOpenAI
from langchain_community.utilities import SQLDatabase
from langchain_experimental.sql import SQLDatabaseChain
from langchain_core.prompts import PromptTemplate
import os

print('hello')

from langchain_core.example_selectors import SemanticSimilarityExampleSelector
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.vectorstores import Chroma

from langchain_core.prompts import FewShotPromptTemplate
from langchain_core.prompts import PromptTemplate
from langchain_classic.chains.sql_database.prompt import PROMPT_SUFFIX

os.environ["OPENAI_API_KEY"] = api_key

llm = ChatOpenAI(
    model="gpt-3.5-turbo",
    temperature=0
)
# Database Connection
db = SQLDatabase.from_uri(
    "mssql+pyodbc://@DESKTOP-QML3J7P\\SQLEXPRESS/atliq_tshirt?driver=ODBC+Driver+17+for+SQL+Server&trusted_connection=yes",
    include_tables=["t_shirts", "discounts"]
)
PROMPT = PromptTemplate(
    input_variables=["input", "table_info", "dialect"],
    template="""
Given an input question, create a correct SQL query,
execute it, and use the SQLResult EXACTLY as returned.

Rules:
- Never change numerical values from SQLResult
- Never make up numbers
- If SQLResult is [(308,)], answer must contain 308
-Use only tables provided in table_info.
-Never invent table names.

Question: {input}
"""
)
db_chain = SQLDatabaseChain.from_llm(
    llm,
    db,
    verbose=True,
    prompt=PROMPT
)


##------------ Some Basic Questions ------------
qns1 = db_chain("How many t-shirts do we have left for nike in extra small(XS) size and white color from t_shirts?")

# qns2 = db_chain("How much is the price of the inventory for all small(S) size t-shirts from t_shirts?")
#Giving wrong answer

qns2 = db_chain.run("SELECT SUM(price*stock_quantity) FROM t_shirts WHERE size = 'S'")

# qns3 = db_chain("""
# Calculate the total revenue generated by selling all Levi's t-shirts today.
# Return only the final aggregated revenue after applying discounts.
# """)
# qns3 didn't because it took date column which we don't have it in our discount table. 
# It took date colun because any offer in a store is a limited period offer not for life time. 
# We need to create a sql query for this and feed it manualy

sql_query = """select 
sum((t.price - COALESCE((t.price * d.pct_discount/100), 0)) * t.stock_quantity) as after_discount_amt
from t_shirts t
left join discounts d
on t.t_shirt_id = d.t_shirt_id
where brand = 'Levi'"""

qns3 = db_chain(sql_query)

# "how much is the revenue I got it for levi tshirt give " ##giving wring answers
#qns4 = db_chain.run("Give me the total sales amount before discount for Levi tshirts from t_shirts")
qns4 = db_chain.run("SELECT SUM(price * stock_quantity) FROM t_shirts WHERE brand = 'Levi'")


# qns5 = db_chain.run("How many white color Levi's t shirts we have available?") #this gives the 
#wrong answer instead of summing up the stock_quantity it is counting the occurance.

#so the right query is (SELECT sum(stock_quantity) AS white_levi_stock FROM t_shirts WHERE brand = 'Levi' AND color = 'White')
# so I am doing it hard coded
qns5 = db_chain.run("SELECT sum(stock_quantity) FROM t_shirts WHERE brand = 'Levi' AND color = 'White'")



##-------------- CREATING SHOTS --------------
few_shots = [
    {'Question' : "How many t-shirts do we have left for Nike in XS size and white color?",
     'SQLQuery' : "SELECT sum(stock_quantity) FROM t_shirts WHERE brand = 'Nike' AND color = 'White' AND size = 'XS'",
     'SQLResult': "Result of the SQL query",
     'Answer' : str(qns1)},
    {'Question': "How much is the total price of the inventory for all S-size t-shirts?",
     'SQLQuery':"SELECT SUM(price*stock_quantity) FROM t_shirts WHERE size = 'S'",
     'SQLResult': "Result of the SQL query",
     'Answer': str(qns2)},
    {'Question': "If we have to sell all the Levi’s T-shirts today with discounts applied. How much revenue  our store will generate (post discounts)?" ,
     'SQLQuery' : """SELECT sum(a.total_amount * ((100-COALESCE(discounts.pct_discount,0))/100)) as total_revenue from
(select sum(price*stock_quantity) as total_amount, t_shirt_id from t_shirts where brand = 'Levi'
group by t_shirt_id) a left join discounts on a.t_shirt_id = discounts.t_shirt_id
 """,
     'SQLResult': "Result of the SQL query",
     'Answer': str(qns3)} ,
     {'Question' : "If we have to sell all the Levi’s T-shirts today. How much revenue our store will generate without discount?" ,
      'SQLQuery': "SELECT SUM(price * stock_quantity) FROM t_shirts WHERE brand = 'Levi'",
      'SQLResult': "Result of the SQL query",
      'Answer' : str(qns4)},
    {'Question': "How many white color Levi's shirt I have?",
     'SQLQuery' : "SELECT sum(stock_quantity) FROM t_shirts WHERE brand = 'Levi' AND color = 'White'",
     'SQLResult': "Result of the SQL query",
     'Answer' : str(qns5)
     }
]



few_shots

##------------ Vectorize using Chroma ------------
embeddings = HuggingFaceEmbeddings(model_name='sentence-transformers/all-MiniLM-L6-v2')

# to_vectorize = [" ".join(example.values()) for example in few_shots]
to_vectorize = [
    " ".join(str(v) for v in example.values())
    for example in few_shots
]

to_vectorize

cleaned_few_shots = [
    {k: str(v) for k, v in example.items()}
    for example in few_shots
]

vectorstore = Chroma.from_texts(to_vectorize, embeddings, metadatas=cleaned_few_shots)


##-------- Retriever --------
example_selector = SemanticSimilarityExampleSelector(
    vectorstore=vectorstore,
    k=2,
)

# example_selector.select_examples({"Question": "How many Adidas T shirts I have left in my store?"})

sql_prompt = """You are a MySQL expert. Given an input question, first create a syntactically correct MySQL query to run, then look at the results of the query and return the answer to the input question.
Unless the user specifies in the question a specific number of examples to obtain, query for at most {top_k} results using the LIMIT clause as per MySQL. You can order the results to return the most informative data in the database.
Never query for all columns from a table. You must query only the columns that are needed to answer the question. Wrap each column name in backticks (`) to denote them as delimited identifiers.
Pay attention to use only the column names you can see in the tables below. Be careful to not query for columns that do not exist. Also, pay attention to which column is in which table.
Pay attention to use CURDATE() function to get the current date, if the question involves "today".

Use the following format:

Question: Question here
SQLQuery: Query to run with no pre-amble
SQLResult: Result of the SQLQuery
Answer: Final answer here

No pre-amble.
"""

print(PROMPT_SUFFIX)
# qns1

example_prompt = PromptTemplate(
    input_variables=["Question", "SQLQuery", "SQLResult","Answer",],
    template="\nQuestion: {Question}\nSQLQuery: {SQLQuery}\nSQLResult: {SQLResult}\nAnswer: {Answer}",
)

print(sql_prompt)

few_shot_prompt = FewShotPromptTemplate(
    example_selector=example_selector,
    example_prompt=example_prompt,
    prefix=sql_prompt,
    suffix=PROMPT_SUFFIX,
    input_variables=["input", "table_info", "top_k"], #These variables are used in the prefix and suffix
)


new_chain = SQLDatabaseChain.from_llm(llm, db, verbose=True, prompt=few_shot_prompt)


new_chain("How many white color Levi's shirt I have?")
